# Generated by Django 5.2 on 2025-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('currency_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=15)),
                ('scale', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
