# Generated by Django 5.2 on 2025-05-03 14:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_from', models.DecimalField(decimal_places=4, max_digits=15)),
                ('amount_to', models.DecimalField(decimal_places=4, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_from', to='home.currencyrate')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_to', to='home.currencyrate')),
            ],
        ),
    ]
